export const LANGUAGES = [
  {
    lang: 'English',
    code: 'en-us'
  },
  {
    lang: '中文简体',
    code: 'zh-cn'
  },
  {
    lang: '中文繁体',
    code: 'zh-tw'
  }]
export const SCERET = 'pBnnZUS0OjPeSW2w6MW%EUwjPoSlMDj4'

export const SCHEDULER_CN = {
  date: {
    month_full: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
    month_short: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    day_full: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
    day_short: ['日', '一', '二', '三', '四', '五', '六']
  },
  labels: {
    dhx_cal_today_button: '今天',
    day_tab: '日',
    week_tab: '周',
    month_tab: '月',
    new_event: '新建日程',
    icon_save: '保存',
    icon_cancel: '关闭',
    icon_details: '详细',
    icon_edit: '编辑',
    icon_delete: '删除',
    confirm_closing: '请确认是否撤销修改!',
    confirm_deleting: '是否删除日程?',
    section_description: '描述',
    section_time: '时间范围',
    full_day: '整天',
    confirm_recurring: '请确认是否将日程设为重复模式?',
    section_recurring: '重复周期',
    button_recurring: '禁用',
    button_recurring_open: '启用',
    button_edit_series: '编辑系列',
    button_edit_occurrence: '编辑实例',
    agenda_tab: '议程',
    date: '日期',
    description: '说明',
    year_tab: '今年',
    week_agenda_tab: '议程',
    grid_tab: '电网',
    drag_to_create: 'Drag to create',
    drag_to_move: 'Drag to move',
    message_ok: 'OK',
    message_cancel: 'Cancel',
    next: 'Next',
    prev: 'Previous',
    year: 'Year',
    month: 'Month',
    day: 'Day',
    hour: 'Hour',
    minute: 'Minute',
    repeat_radio_day: '按天',
    repeat_radio_week: '按周',
    repeat_radio_month: '按月',
    repeat_radio_year: '按年',
    repeat_radio_day_type: '每',
    repeat_text_day_count: '天',
    repeat_radio_day_type2: '每个工作日',
    repeat_week: ' 重复 每',
    repeat_text_week_count: '星期的:',
    repeat_radio_month_type: '重复',
    repeat_radio_month_start: '在',
    repeat_text_month_day: '日 每',
    repeat_text_month_count: '月',
    repeat_text_month_count2_before: '每',
    repeat_text_month_count2_after: '月',
    repeat_year_label: '在',
    select_year_day2: '的',
    repeat_text_year_day: '日',
    select_year_month: '月',
    repeat_radio_end: '无结束日期',
    repeat_text_occurences_count: '次结束',
    repeat_radio_end2: '重复',
    repeat_radio_end3: '结束于',
    month_for_recurring: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
    day_for_recurring: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六']
  }
}

export const SCHEDULER_TW = {
  date: {
    month_full: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
    month_short: ['1月', '2月', '3月', '4月', '5月', '6月', '7月', '8月', '9月', '10月', '11月', '12月'],
    day_full: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六'],
    day_short: ['日', '一', '二', '三', '四', '五', '六']
  },
  labels: {
    dhx_cal_today_button: '今天',
    day_tab: '日',
    week_tab: '周',
    month_tab: '月',
    new_event: '新建日程',
    icon_save: '保存',
    icon_cancel: '關閉',
    icon_details: '詳細',
    icon_edit: '編輯',
    icon_delete: '刪除',
    confirm_closing: '請確認是否撤銷修改!',
    confirm_deleting: '是否刪除日程?',
    section_description: '描述',
    section_time: '時間範圍',
    full_day: '整天',
    confirm_recurring: '請確認是否將日程設為重複模式?',
    section_recurring: '重複週期',
    button_recurring: '禁用',
    button_recurring_open: '啟用',
    button_edit_series: '編輯系列',
    button_edit_occurrence: '編輯實例',
    agenda_tab: '議程',
    date: '日期',
    description: '說明',
    year_tab: '今年',
    week_agenda_tab: '議程',
    grid_tab: '電網',
    drag_to_create: 'Drag to create',
    drag_to_move: 'Drag to move',
    message_ok: 'OK',
    message_cancel: 'Cancel',
    next: 'Next',
    prev: 'Previous',
    year: 'Year',
    month: 'Month',
    day: 'Day',
    hour: 'Hour',
    minute: 'Minute',
    repeat_radio_day: '按天',
    repeat_radio_week: '按周',
    repeat_radio_month: '按月',
    repeat_radio_year: '按年',
    repeat_radio_day_type: '每',
    repeat_text_day_count: '天',
    repeat_radio_day_type2: '每個工作日',
    repeat_week: ' 重複 每',
    repeat_text_week_count: '星期的:',
    repeat_radio_month_type: '重複',
    repeat_radio_month_start: '在',
    repeat_text_month_day: '日 每',
    repeat_text_month_count: '月',
    repeat_text_month_count2_before: '每',
    repeat_text_month_count2_after: '月',
    repeat_year_label: '在',
    select_year_day2: '的',
    repeat_text_year_day: '日',
    select_year_month: '月',
    repeat_radio_end: '無結束日期',
    repeat_text_occurences_count: '次結束',
    repeat_radio_end2: '重複',
    repeat_radio_end3: '結束於',
    month_for_recurring: ['一月', '二月', '三月', '四月', '五月', '六月', '七月', '八月', '九月', '十月', '十一月', '十二月'],
    day_for_recurring: ['星期日', '星期一', '星期二', '星期三', '星期四', '星期五', '星期六']
  }
}

export const SCHEDULER_US = {
  date: {
    month_full: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    month_short: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], day_full: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'], day_short: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']
  },
  labels: {
    dhx_cal_today_button: 'Today',
    day_tab: 'Day',
    week_tab: 'Week',
    month_tab: 'Month',
    new_event: 'New event',
    icon_save: 'Save',
    icon_cancel: 'Cancel',
    icon_details: 'Details',
    icon_edit: 'Edit',
    icon_delete: 'Delete',
    confirm_closing: '',
    confirm_deleting: 'Event will be deleted permanently, are you sure?',
    section_description: 'Description',
    section_time: 'Time period',
    full_day: 'Full day',
    confirm_recurring: 'Do you want to edit the whole set of repeated events?',
    section_recurring: 'Repeat event',
    button_recurring: 'Disabled',
    button_recurring_open: 'Enabled',
    button_edit_series: 'Edit series',
    button_edit_occurrence: 'Edit occurrence',
    agenda_tab: 'Agenda',
    date: 'Date',
    description: 'Description',
    year_tab: 'Year',
    week_agenda_tab: 'Agenda',
    grid_tab: 'Grid',
    drag_to_create: 'Drag to create',
    drag_to_move: 'Drag to move',
    message_ok: 'OK',
    message_cancel:
    'Cancel', next: 'Next', prev: 'Previous',
    year: 'Year', month: 'Month', day: 'Day',
    hour: 'Hour', minute: 'Minute',
    repeat_radio_day: 'Daily',
    repeat_radio_week: 'Weekly',
    repeat_radio_month: 'Monthly',
    repeat_radio_year: 'Yearly',
    repeat_radio_day_type: 'Every',
    repeat_text_day_count: 'day',
    repeat_radio_day_type2: 'Every workday',
    repeat_week: ' Repeat every',
    repeat_text_week_count: 'week next days:',
    repeat_radio_month_type: 'Repeat',
    repeat_radio_month_start: 'On',
    repeat_text_month_day: 'day every',
    repeat_text_month_count: 'month',
    repeat_text_month_count2_before: 'every',
    repeat_text_month_count2_after: 'month',
    repeat_year_label: 'On',
    select_year_day2: 'of',
    repeat_text_year_day: 'day',
    select_year_month: 'month',
    repeat_radio_end: 'No end date',
    repeat_text_occurences_count: 'occurrences',
    repeat_radio_end2: 'After',
    repeat_radio_end3: 'End by',
    month_for_recurring: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    day_for_recurring: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
  }
}
